# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 11:45:49 2024

@author: passieux
"""

import numpy as np  
import pyxel as px

# building a virtual volume image of a cylinder
f = px.Volume('')
x = np.arange(80)
y = np.arange(80)
z = np.arange(100)
X, Y, Z = np.meshgrid(x, y, z)
f.pix = (((X-40)**2 + (Y-40)**2) < 35**2) * 255
f.pix[:, :, :5] = 0
f.pix[:, :, -5:] = 0
f.GaussianFilter(0.8)
f.Plot()

m, cam = px.MeshFromImage3D(f, thrs=128, facet_size=8, cell_size=8)

m.Plot()

px.PlotMeshImage3d(f, m, cam)


# %%
from skimage import measure
thrs = 128
facet_size = 8
cell_size = 8
pix = f.pix
pix[:, :, 0] = 0
pix[:, :, -1] = 0
pix[:, 0, :] = 0
pix[:, -1, :] = 0
pix[0, :, :] = 0
pix[-1, :, :] = 0
verts, faces, _ , _ = measure.marching_cubes(pix, level=thrs, spacing=(1,1,1), allow_degenerate=False)
ms = px.Mesh({2: faces}, verts, dim=3)
# ms.Plot()
ms.Write('tmp.stl')


# %%
import gmsh 
gmsh.initialize()
gmsh.clear()
gmsh.merge('tmp.stl')

# We first classify ("color") the surfaces by splitting the original surface
# along sharp geometrical features. This will create new discrete surfaces,
# curves and points.

# Angle between two triangles above which an edge is considered as sharp,
# retrieved from the ONELAB database (see below):
angle = gmsh.onelab.getNumber('Parameters/Angle for surface detection')[0]

# For complex geometries, patches can be too complex, too elongated or too
# large to be parametrized; setting the following option will force the
# creation of patches that are amenable to reparametrization:
forceParametrizablePatches = gmsh.onelab.getNumber(
    'Parameters/Create surfaces guaranteed to be parametrizable')[0]

# For open surfaces include the boundary edges in the classification
# process:
includeBoundary = True

# Force curves to be split on given angle:
curveAngle = 180

gmsh.model.mesh.classifySurfaces(angle * math.pi / 180., includeBoundary,
                                 forceParametrizablePatches,
                                 curveAngle * math.pi / 180.)

# Create a geometry for all the discrete curves and surfaces in the mesh, by
# computing a parametrization for each one
gmsh.model.mesh.createGeometry()

# Note that if a CAD model (e.g. as a STEP file, see `t20.py') is available
# instead of an STL mesh, it is usually better to use that CAD model instead
# of the geometry created by reparametrizing the mesh. Indeed, CAD
# geometries will in general be more accurate, with smoother
# parametrizations, and will lead to more efficient and higher quality
# meshing. Discrete surface remeshing in Gmsh is optimized to handle dense
# STL meshes coming from e.g. imaging systems, where no CAD is available; it
# is less well suited for the poor quality STL triangulations (optimized for
# size, with e.g. very elongated triangles) that are usually generated by
# CAD tools for e.g. 3D printing.

# Create a volume from all the surfaces
s = gmsh.model.getEntities(2)
l = gmsh.model.geo.addSurfaceLoop([e[1] for e in s])
gmsh.model.geo.addVolume([l])

gmsh.model.geo.synchronize()

# We specify element sizes imposed by a size field, just because we can :-)
f = gmsh.model.mesh.field.add("MathEval")
if gmsh.onelab.getNumber('Parameters/Apply funny mesh size field?')[0]:
    gmsh.model.mesh.field.setString(f, "F", "2*Sin((x+y)/5) + 3")
else:
    gmsh.model.mesh.field.setString(f, "F", "4")
gmsh.model.mesh.field.setAsBackgroundMesh(f)

gmsh.model.mesh.generate(3)
gmsh.write('t13.msh')
